config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to:'homes#top'
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :home_countries, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :groups, only: [:index, :destroy, :show] do
      resources :chats, only: [:index, :destroy]
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    get '/confirm' => 'users#confirm'
    patch '/withdraw' => 'users#withdraw'
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    resources :posts do
      resources :comments, except: :new
      resource :favorite, only: [:create, :destroy]
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resource :group_user, only: [:create, :destroy]
      resources :chats, only: [:index, :create, :destroy]
    end
    resources :notifications, only: [:update]
  end
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_genre, only: [:edit, :update]

  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(20)
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "Successfully saved."
    else
      @genres = Genre.page(params[:page]).per(20)
      flash.now[:alert] = "Failed to save."
      render :index
    end
  end
  
  def update
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "Successfully saved."
    else
      flash.now[:alert] = "Failed to save."
      render :edit
    end
  end

  def edit
  end
  
  private
  
  def ensure_genre
    @genre = Genre.find(params[:id])
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model: genre , url: url do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit submit,class:"btn btn-success" %>
<% end %>

app/views/admin/genres/edit.html.erb
<%= stylesheet_link_tag 'admin/country_genre', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <h1 class="page-title-long">GENRES EDIT</h1>
  <div class="row">
    <div class="col-6 my-5">
      <%= render 'form', genre: @genre , url: admin_genre_path(@genre), submit: 'save'%>
      </br>
      <%= link_to 'BACK', 'javascript:history.back()' ,class:"btn-back" %></br></br>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<%= stylesheet_link_tag 'admin/country_genre', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <h1 class="page-title-long">GENRES</h1>
  <div class="row">
    <div class="col-md-6 my-5">
      <%= render 'form', genre: @genre , url: admin_genres_path, submit: 'New Registration' %>
    </div>
    <div class="col-md-6">
      <table class="table table-responsive-md">
        <thead>
          <tr>
            <th>List</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "Edit",edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @genres %>
    </div>
    <%= link_to 'BACK', 'javascript:history.back()' ,class:"btn-back" %></br></br>
  </div>
</div>