config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to:'homes#top'
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :home_countries, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :groups, only: [:index, :destroy, :show] do
      resources :chats, only: [:index, :destroy]
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    get '/confirm' => 'users#confirm'
    patch '/withdraw' => 'users#withdraw'
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    resources :posts do
      resources :comments, except: :new
      resource :favorite, only: [:create, :destroy]
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resource :group_user, only: [:create, :destroy]
      resources :chats, only: [:index, :create, :destroy]
    end
    resources :notifications, only: [:update]
  end
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :genre
  
  has_one_attached :image
  
  validates :genre_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true
  validates :ingredient, presence: true
  validates :method, presence: true
  validates :level, presence: true
  validates :originality, presence: true
  validates :image, presence: true
  
  enum level: { Beginner: 0, Intermediate: 1, Advanced: 2 }
  enum originality: { Local_cuisine: 0, Original: 1, }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type:'image/jpg')
    end
      image.variant(resize_to_limit: [300, 300]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
    
  scope :search, -> (keyword) { where('title LIKE :keyword OR ingredient LIKE :keyword', keyword: "%#{keyword}%") }
  scope :by_genre, ->(genre_id) { where(genre_id: genre_id) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_originality, ->(originality) { where(originality: originality) }
  scope :by_home_country, ->(country_id) { joins(user: :home_country).where('home_countries.id = ?', country_id) }
  scope :latest, -> {order(created_at: :desc) }
  scope :oldest, -> {order(created_at: :asc) }
  scope :most_favorite, -> {
    select("posts.*, COUNT(favorites.id) AS favorites_count")
    .left_joins(:favorites)
    .group("posts.id")
    .order(favorites_count: :desc)
  }
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @keyword = params[:keyword]
    @by_genre = params[:genre_id]
    @by_home_country = params[:home_country_id]
    @by_level = params[:level]
    @by_originality = params[:originality]

    @posts = Post.page(params[:page]).per(20)
    @posts = @posts.search(@keyword) if @keyword.present?
    @posts = @posts.by_genre(@by_genre) if @by_genre.present?
    @posts = @posts.by_home_country(@by_home_country) if @by_home_country.present?
    @posts = @posts.by_level(@by_level) if @by_level.present?
    @posts = @posts.by_originality(@by_originality) if @by_originality.present?
    @posts = @posts.latest if params[:order] == "latest"
    @posts = @posts.oldest if params[:order] == "oldest"
    @posts = @posts.most_favorite if params[:order] == "most_favorite"
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_search.html.erb
<div id="search-menu">
  <div class ="search-box">
    <div class ="search-box-content">
      <h2>Search</h2>
      <h5>Sort by</h5>
        <%= link_to "Newest", admin_posts_path(order: "latest") %></br>
        <%= link_to "Oldest", admin_posts_path(order: "oldest") %></br>
        <%= link_to "Popularity", admin_posts_path(order: "most_favorite") %></br>
      <h5>Browse By</h5>
        <%= form_with local: true, method: :get do |f| %>
          <%= f.label :genre_id %></br>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: "--Select Genre--"} %></br>
          <%= f.label :home_country_id %></br>
          <%= f.collection_select :home_country_id, HomeCountry.all, :id, :name, { include_blank: "--Select Country--"} %></br>
          <%= f.label :level %></br>
          <%= f.select :level, Post.levels.keys,  { include_blank: "--Select Level--"} %></br>
          <%= f.label :originality %></br>
          <%= f.select :originality, Post.originalities.keys,  { include_blank: "--Select Originality--"} %></br>
          <%= f.label :keyword %></br>
          <%= f.text_field :keyword, placeholder: "--input keyword--" %></br></br>
          <%= f.submit "Search" ,class:"search-submit",class:"btn_search" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<%= stylesheet_link_tag 'admin/posts', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1 class="page-title">RECIPES</h1>
<div id="search-icon">
  <%= link_to("#", class: "menu-trigger button") do %>
    <span><i class="fa-solid fa-magnifying-glass"></i></span>
  <% end %>
</div>
<div class='container'>
  <div class="row">
    <%= render 'admin/posts/search' %>
    <div class = 'items-box'>
      <div class="box">
      <% @posts.each do |post| %>
        <li class="card">
          <div class="card-img">
            <%= link_to admin_post_path(post) do %>
              <%= image_tag post.get_image, size: "199x130" %>
            <% end %>
          </div>
          <div class="card-content">
            <h1 class="card-title">
              <%= post.title %>
            </h1>
            <p class="card-text">
              <%= post.genre.name %></br>
              Level: <%= post.level %></br>
              <%= image_tag post.user.home_country.image, size: "20x20" %>
              By <%= post.user.nickname %>&nbsp;</br>
              <%= link_to post_comments_path(post) do %>
                <i class="fa-regular fa-comment"></i>&nbsp;<%= post.comments.count %>&nbsp;
              <% end %>
              <i class="fa-solid fa-heart"></i>&nbsp;<%= post.favorites.count %>
            </p>
          </div>
        </li>
      <% end %>
      </div>
    </div>
  </div>
   <%= paginate @posts %>
</div>
<div class="back">
  <%= link_to 'BACK', 'javascript:history.back()' ,class:"btn-back" %>
</div>

<script>
  $(function() {
    $('.menu-trigger').on('click', function(event) {
      $(this).toggleClass('active');
      $('#search-menu').fadeToggle();
      event.preventDefault();
    });
  });
</script>

app/views/admin/posts/show.html.erb
<%= stylesheet_link_tag 'admin/posts', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1 class="page-title-long">RECIPE DETAIL</h1>
<div class='container'>
  <div class = "row mt-3 justify-content-between">
    <div class = 'col-lg-6 main-image'>
      <%= image_tag @post.get_image ,size: "400x300" %>
    </div>
    <div class = 'col-lg-6 main-title'>
      <h1><%= @post.title %></h1>
      <p><%= @post.body %></p>
      <table class="recipe-detail">
        <tbody>
          <tr>
            <th>Genre</th>
            <td><%= @post.genre.name %></td>
          </tr>
          <tr>
            <th>Level</th>
            <td><%= @post.level %></td>
          </tr>
          <tr>
            <th>Originality</th>
            <td><%= @post.originality %></td>
          </tr>
          <tr>
            <th>Country</th>
            <td><%= image_tag @post.user.home_country.image, size: "20x20" %></td>
          </tr>
          <tr>
            <td>comments:&nbsp;<%= @post.comments.count %>&nbsp;&nbsp;</td>
            <td>
              <i class="fa-solid fa-heart"></i>&nbsp;<%= @post.favorites.count %>
            </td>
          </tr>
        </tbody>
      </table>
      </br>
      <%= link_to "Destroy",admin_post_path(@post),  method: :delete , data: { confirm: 'Do you really want to delete it?' },class:"btn btn-danger" %>
    </div>
  </div>
    <div class="row mt-5">
      <div class ="col-lg-6 long-text">
        <h1>Ingredient</h1>
        <p><%= safe_join(@post.ingredient.split("\n"),tag(:br)) %></p>
      </div>
      <div class ="col-lg-6 long-text">
        <h1>Method</h1>
        <p><%= safe_join(@post.method.split("\n"),tag(:br)) %></p>
      </div>
    </div>
      <div class="row mt-5">
        <div class="col">
          <h1>
            <span id="comment_counter">
              <%= render "public/comments/counter", post: @post %>
            </span>
          </h1>
            <% @post.comments.order(created_at: :desc).each do |comment| %>
            <ul class="list-group">
              <li class="list-group-item">
                <span class="sentiment-score">Sentiment analysis<%= comment.score %></span></br>
                <strong><%= comment.user.nickname %></strong></br>
                  <%= comment.created_at.strftime('%Y/%m/%d') %></br>
                  <%= comment.body %></br>
                  <%= link_to "destroy", post_comment_path(comment.post,comment), method: :delete %>
              </li>
            </ul>
            <% end %>
        </div>
      </div>
      </br>
      <%= link_to 'BACK', 'javascript:history.back()' ,class:"btn-back" %></br></br>
    </div>
    