config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to:'homes#top'
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :home_countries, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :groups, only: [:index, :destroy, :show] do
      resources :chats, only: [:index, :destroy]
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    get '/confirm' => 'users#confirm'
    patch '/withdraw' => 'users#withdraw'
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    resources :posts do
      resources :comments, except: :new
      resource :favorite, only: [:create, :destroy]
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resource :group_user, only: [:create, :destroy]
      resources :chats, only: [:index, :create, :destroy]
    end
    resources :notifications, only: [:update]
  end
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :permits, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  def is_owned_by?(user)
    owner_id == user.id
  end

  def owner_nickname
    owner.nickname
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  private

  def owner
    User.find_by(id: owner_id)
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:keyword].present?
      @groups = Group.page(params[:page]).per(20).order(created_at: :desc).where('groups.name LIKE :keyword OR groups.introduction LIKE :keyword', keyword: "%#{params[:keyword]}%")
    else
    @groups = Group.page(params[:page]).per(20).order(created_at: :desc)
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_groups_path
  end


end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/index.html.erb
<%= stylesheet_link_tag 'admin/groups', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <h1 class="page-title-long">TOURS</h1>
  <div class="search_form-2">
    <%= form_with local: true, method: :get do |f| %>
      <%= f.text_field :keyword, placeholder: "--input keyword--" %>
      <%= f.submit "Search" ,class:"search-submit",class:"btn_search" %>
    <% end %>
  </div>
  <div class="row">
    <div class="col">
      <% @groups.each do |group| %>
      <div class="list-group">
        <div class="box-title">
          <%= group.name %>
        </div>
        <ul>
          <li><strong>Organizer:<%= group.owner_nickname %></strong></li>
          <li><i class="fa-solid fa-users"></i>Members: <%= group.group_users.count %></li>
          <li><%= safe_join(word_wrap(group.introduction).split("\n"),tag(:br)) %></li>
          <li>
            <div class="link-button">
              <%= link_to 'Show', admin_group_path(group) %>/&nbsp;
              <%= link_to 'destroy', admin_group_path(group), data: { confirm: 'Do you really want to delete it?' },method: :delete %>
            </div>
          </li>
        </ul>
      </div>
      <% end %>
       <%= paginate @groups %>
      </br>
      <%= link_to 'BACK', 'javascript:history.back()' ,class:"btn-back" %></br></br>
    </div>
  </div>
</div>

app/views/admin/groups/show.html.erb
<%= stylesheet_link_tag 'admin/groups', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <h1 class="page-title-long">TOUR DETAIL</h1>
  <div class="row mt-4">
    <div class="col-md-10 col-sm-1">
      <h3>Organizer: <%= @group.owner_nickname %></h3>
    </div>
    <div class="col-md-2 col-sm-1">
      <%= link_to "Chat Room" ,admin_group_chats_path(@group) ,class:"button"%>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="list-group">
        <div class="box-title"><%= @group.name %></div>
        <ul>
          <li><%= safe_join(word_wrap(@group.introduction).split("\n"),tag(:br)) %></li>
          <li></br></li>
          <li>
            <div class="link-button">
                <%= link_to 'destroy', admin_group_path(@group), data: { confirm: 'Do you really want to delete it?' }, method: :delete %>
            </div>
          </li>
        </ul>
      </div>
      <div class="member">
        <h1>Members:<%= @group.group_users.count %></h1>
          <div class="member-list">
          <% @group.users.each do |user| %>
            <div>
              <i class="fa-solid fa-user-large"></i><%= user.nickname %>
            </div>
          <% end %>
          </div>
      </div>
      </br>
      <%= link_to 'BACK', 'javascript:history.back()' ,class:"btn-back" %></br></br>
    </div>
  </div>
</div>