config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to:'homes#top'
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :home_countries, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :groups, only: [:index, :destroy, :show] do
      resources :chats, only: [:index, :destroy]
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to:'homes#top'
    get '/my_page' => 'users#mypage'
    get '/confirm' => 'users#confirm'
    patch '/withdraw' => 'users#withdraw'
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :users, only: [:edit, :show, :update] do
      member do
        get :favorite
      end
    end
    resources :posts do
      resources :comments, except: :new
      resource :favorite, only: [:create, :destroy]
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resource :group_user, only: [:create, :destroy]
      resources :chats, only: [:index, :create, :destroy]
    end
    resources :notifications, only: [:update]
  end
  devise_scope :user do
    post "users/guest_sign_in" , to: "public/sessions#guest_sign_in"
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
  validates :message, presence: true, length: { maximum: 140 }
  
  scope :search_by_message, -> (search) { where('message LIKE ?', "%#{search}%") }
  
end

app/models/comment.rb
class Comment < ApplicationRecord

 belongs_to :user
 belongs_to :post
 has_one :notification, as: :notifiable, dependent: :destroy 

 validates :body, presence: true
 
 scope :search_by_body, -> (search) { where('body LIKE ?', "%#{search}%") }
 scope :search_by_min_score, -> (min_score) { where('score >= ?', min_score) }
 scope :search_by_max_score, -> (max_score) { where('score <= ?', max_score) }
 
 after_create do
  create_notification(user_id: post.user_id)
 end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
 belongs_to :user
 belongs_to :post
 has_one :notification, as: :notifiable, dependent: :destroy 
 
 validates :user_id, uniqueness: {scope: :post_id}
 
 after_create do
  create_notification(user_id: post.user_id)
 end
 
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
  
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :permits, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  def is_owned_by?(user)
    owner_id == user.id
  end

  def owner_nickname
    owner.nickname
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  private

  def owner
    User.find_by(id: owner_id)
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
 belongs_to :user
 belongs_to :group
  
end

app/models/home_country.rb
class HomeCountry < ApplicationRecord
  
  has_many :users, dependent: :destroy
  has_one_attached :image
  
  validates :name, presence: true, uniqueness: true
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type:'image/jpg')
    end
      image.variant(resize_to_limit: [100, 100]).processed
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_one :notification, as: :notifiable, dependent: :destroy

  after_create do
  create_notification(user_id: group.owner_id)
 end

end

app/models/post.rb
class Post < ApplicationRecord
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :genre
  
  has_one_attached :image
  
  validates :genre_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true
  validates :ingredient, presence: true
  validates :method, presence: true
  validates :level, presence: true
  validates :originality, presence: true
  validates :image, presence: true
  
  enum level: { Beginner: 0, Intermediate: 1, Advanced: 2 }
  enum originality: { Local_cuisine: 0, Original: 1, }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type:'image/jpg')
    end
      image.variant(resize_to_limit: [300, 300]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
    
  scope :search, -> (keyword) { where('title LIKE :keyword OR ingredient LIKE :keyword', keyword: "%#{keyword}%") }
  scope :by_genre, ->(genre_id) { where(genre_id: genre_id) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_originality, ->(originality) { where(originality: originality) }
  scope :by_home_country, ->(country_id) { joins(user: :home_country).where('home_countries.id = ?', country_id) }
  scope :latest, -> {order(created_at: :desc) }
  scope :oldest, -> {order(created_at: :asc) }
  scope :most_favorite, -> {
    select("posts.*, COUNT(favorites.id) AS favorites_count")
    .left_joins(:favorites)
    .group("posts.id")
    .order(favorites_count: :desc)
  }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  belongs_to :home_country
  has_many :chats, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  validates :name, presence: true
  validates :nickname, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, length: { minimum: 6 }, on: :create


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL ) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "guestuser"
      user.home_country_id = "1"
      user.nickname = "guestuser"
    end
  end
  
  before_update :delete_associated_records, if: -> { is_active_changed? && !is_active }
  
  def delete_associated_records
      posts.destroy_all
      comments.destroy_all
      favorites.destroy_all
      groups.destroy_all
      group_users.destroy_all
      Group.where(owner_id: id).destroy_all
      chats.destroy_all
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/chats_helper.rb
module Admin::ChatsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div id="notice" class="alert alert-warning text-center">
    <%= flash[:notice] %>
  </div>
<% elsif flash.now[:alert] %>
  <div id="alert" class="alert alert-danger text-center">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid", style="background-color: #F6AD67;">
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>©Yuka Taguchi</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to 'Travel By Cooking', root_path, data: {"turbolinks" => false} ,class:"navbar-brand text-white" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li><%= link_to 'User',admin_users_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Recipe',admin_posts_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Genre',admin_genres_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Country',admin_home_countries_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Comment',admin_comments_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Tour',admin_groups_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Log out',destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %></li>
            <% elsif user_signed_in? %>
              <li>
                <%= link_to my_page_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-house"></i> Mypage
                <% end %>
              </li>
              <li>
                <%= link_to groups_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-ship"></i> Tour
                <% end %>
              </li>
              <li>
                <%= link_to posts_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-utensils"></i> Recipes
                <% end %>
              </li>
              <li class="dropdown">
                <button class="btn text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa-solid fa-message"></i> Notification
                  <span class="badge badge-light"><%= current_user.notifications.where(read: false).count %></span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <% if current_user.notifications.where(read: false).any? %>
                    <small class="dropdown-item disabled">Unread Notification</small>
                    <% current_user.notifications.where(read: false).order(created_at: :desc).each do |notification| %>
                      <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                    <% end %>
                  <% else %>
                    <span class="dropdown-item disabled">No unread notifications</span>
                  <% end %>
                </div>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-truck-fast"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-plane-up"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-door-open"></i> Log in
                <% end %>
              </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TBC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f4a6fb0793.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>
    <main class="flex-grow-1">
      <div id="flash-message">
        <%= render 'layouts/flash' %>
      </div>

    <script>
     setTimeout(function() {
      document.getElementById('notice')?.remove();  // noticeが存在する場合に非表示にします
      document.getElementById('alert')?.remove();  // alertが存在する場合に非表示にします
     }, 3000);  // 5000ミリ秒（5秒）後に実行します
    </script>

    <%= yield %>
    </br>
    </main>
    
    <%= render 'layouts/footer' %>
    
  </body>
</html>